name: Global CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Installing dependencies
        run: npm ci

      - name: Linting code
        run: npm run lint

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Installing dependencies
        run: npm ci

      - name: Linting code
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Installing dependencies
        run: npm ci

      - name: Linting code
        run: npm run test
